[package]
name = "gated_dna_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "gated_dna_integrity"

[dependencies]
hdi = { workspace = true }
ethers-core = { version = "2.0.5"}
hex = "0.4.3"


serde = { workspace = true }
