[package]
name = "lobby"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "lobby"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

lobby_integrity = { workspace = true } 
